export const THEMES = {
  green: { color: '#00ff41', glow: 'rgba(0, 255, 65, 0.6)', dim: 'rgba(0, 255, 65, 0.3)', name: 'Phosphor Green' },
  amber: { color: '#ffb000', glow: 'rgba(255, 176, 0, 0.6)', dim: 'rgba(255, 176, 0, 0.3)', name: 'Amber' },
  blue:  { color: '#00d4ff', glow: 'rgba(0, 212, 255, 0.6)', dim: 'rgba(0, 212, 255, 0.3)', name: 'Ice Blue' },
  white: { color: '#f0f0f0', glow: 'rgba(240, 240, 240, 0.5)', dim: 'rgba(240, 240, 240, 0.25)', name: 'Monochrome' },
  // New themes
  red:   { color: '#ff3355', glow: 'rgba(255, 51, 85, 0.55)', dim: 'rgba(255, 51, 85, 0.28)', name: 'Crimson CRT' },
  violet:{ color: '#b084ff', glow: 'rgba(176, 132, 255, 0.55)', dim: 'rgba(176, 132, 255, 0.28)', name: 'Synthwave' },
  cyan:  { color: '#5eead4', glow: 'rgba(94, 234, 212, 0.55)', dim: 'rgba(94, 234, 212, 0.28)', name: 'Vaporwave' },
  pink:  { color: '#ff77b5', glow: 'rgba(255, 119, 181, 0.55)', dim: 'rgba(255, 119, 181, 0.28)', name: 'Bubblegum' },
}

export const BOOT_SEQUENCE = [
  { text: 'AMIBIOS (C) 2026 American Megatrends, Inc.', delay: 100 },
  { text: 'PORTFOLIO BIOS v4.2.0 — Build 20260405', delay: 200 },
  { text: '', delay: 100 },
  { text: 'CPU: Neural Processing Unit @ 3.8 GHz', delay: 150 },
  { text: 'Memory Test: 32768 MB OK', delay: 300 },
  { text: '', delay: 50 },
  { text: 'Detecting Primary Drive.......... [SSD 1TB] OK', delay: 400 },
  { text: 'Detecting USB Devices............ [Keyboard] OK', delay: 200 },
  { text: 'Initializing Network............. [Connected] OK', delay: 300 },
  { text: '', delay: 100 },
  { text: 'Loading Portfolio OS v2.0.........', delay: 500 },
  { text: '████████████████████████████████████ 100%', delay: 600 },
  { text: '', delay: 100 },
  { text: '============================================', delay: 50 },
  { text: '  PORTFOLIO TERMINAL v2.0 — SYSTEM READY', delay: 50 },
  { text: '============================================', delay: 50 },
  { text: '', delay: 50 },
  { text: 'Welcome! Type "help" to see available commands.', delay: 100 },
  { text: '', delay: 50 },
]

export const COMMANDS = [
  'help', 'about', 'skills', 'projects', 'contact',
  'education', 'experience', 'clear', 'theme', 'matrix',
  'neofetch', 'weather', 'fortune', 'games', 'ascii-art', 'history',
  'sound', 'sudo rm -rf /',
  // New commands
  'date', 'time', 'echo', 'whoami', 'uname', 'uptime',
  'coffee', 'cowsay', 'stats', 'banner', 'cal', 'rickroll',
  'share',
]

export const HELP_TEXT = [
  '┌─────────────────────────────────────────────┐',
  '│           AVAILABLE COMMANDS                 │',
  '├─────────────────────────────────────────────┤',
  '│  help        — Show this help message        │',
  '│  about       — About me                      │',
  '│  skills      — Technical skills              │',
  '│  projects    — Featured projects              │',
  '│  contact     — Get in touch                   │',
  '│  education   — Education history              │',
  '│  experience  — Work experience                │',
  '│  neofetch    — System info (ASCII art)        │',
  '│  weather <c> — ASCII weather for a city       │',
  '│  fortune     — Random programming quote        │',
  '│  games       — Number guessing game           │',
  '│  ascii-art   — Random ASCII art               │',
  '│  history     — Show last 20 commands          │',
  '│  sound on|off— Toggle typing sound effects    │',
  '│  theme <c>   — Change color theme             │',
  '│  matrix      — 🐇 Follow the white rabbit    │',
  '│  clear       — Clear terminal                 │',
  '├─────────────────────────────────────────────┤',
  '│  ─── FUN ───                                 │',
  '│  banner <w>  — Big ASCII banner text          │',
  '│  cowsay <m>  — Cow says something              │',
  '│  coffee      — Get a virtual coffee           │',
  '│  rickroll    — You know the drill             │',
  '│  ─── SYSTEM ───                              │',
  '│  date / time — Current date and time          │',
  '│  cal         — Calendar for current month     │',
  '│  echo <text> — Print text back                │',
  '│  whoami / uname / uptime                      │',
  '│  stats       — Session statistics             │',
  '│  share       — Copy URL to clipboard          │',
  '├─────────────────────────────────────────────┤',
  '│  Themes: green amber blue white red violet   │',
  '│          cyan pink                            │',
  '│  ↑/↓ history   Tab auto-complete   Ctrl+L clear│',
  '└─────────────────────────────────────────────┘',
]

export const ABOUT_TEXT = [
  '',
  '  ╔══════════════════════════════════════════╗',
  '  ║             ABOUT ME                     ║',
  '  ╚══════════════════════════════════════════╝',
  '',
  '  Hey there! 👋',
  '',
  '  I\'m a Full-Stack Developer who loves building',
  '  things that live on the internet. I turn coffee',
  '  into code and ideas into products.',
  '',
  '  When I\'m not pushing commits, you\'ll find me',
  '  exploring new tech, contributing to open source,',
  '  or tweaking my dev setup for the nth time.',
  '',
  '  Currently based in the Pacific Northwest 🌲',
  '  Open to collaboration and new opportunities!',
  '',
]

export const SKILLS_DATA = [
  { name: 'JavaScript / TypeScript', level: 92 },
  { name: 'React / Next.js', level: 90 },
  { name: 'Node.js / Express', level: 85 },
  { name: 'Python', level: 80 },
  { name: 'PostgreSQL / MongoDB', level: 78 },
  { name: 'Docker / DevOps', level: 72 },
  { name: 'AWS / Cloud', level: 70 },
  { name: 'Go', level: 55 },
]

export const PROJECTS_TEXT = [
  '',
  '  ╔══════════════════════════════════════════╗',
  '  ║          FEATURED PROJECTS               ║',
  '  ╚══════════════════════════════════════════╝',
  '',
  '  ┌─ 01 ─────────────────────────────────────┐',
  '  │ DevFlow — Team Collaboration Platform     │',
  '  │ Real-time project management with live    │',
  '  │ cursors, Kanban boards, and GitHub sync.  │',
  '  │ Stack: React, Node.js, WebSockets, Redis  │',
  '  │ ★ 240 stars on GitHub                     │',
  '  └──────────────────────────────────────────┘',
  '',
  '  ┌─ 02 ─────────────────────────────────────┐',
  '  │ SnapDB — Lightweight JSON Database        │',
  '  │ Zero-config embedded database for small   │',
  '  │ projects. Query API inspired by MongoDB.  │',
  '  │ Stack: TypeScript, Node.js, LevelDB       │',
  '  │ ★ 180 stars on GitHub                     │',
  '  └──────────────────────────────────────────┘',
  '',
  '  ┌─ 03 ─────────────────────────────────────┐',
  '  │ CloudDeploy — One-Click Deployments       │',
  '  │ CLI tool for deploying apps to any cloud  │',
  '  │ provider with a single command.           │',
  '  │ Stack: Go, Docker, Terraform, AWS/GCP     │',
  '  │ ★ 95 stars on GitHub                      │',
  '  └──────────────────────────────────────────┘',
  '',
  '  ┌─ 04 ─────────────────────────────────────┐',
  '  │ retro-terminal — This Portfolio!          │',
  '  │ The site you\'re looking at right now.     │',
  '  │ CRT terminal with interactive commands.   │',
  '  │ Stack: React, Vite, Tailwind, Framer      │',
  '  └──────────────────────────────────────────┘',
  '',
]

export const CONTACT_TEXT = [
  '',
  '  ╔══════════════════════════════════════════╗',
  '  ║             CONTACT                      ║',
  '  ╚══════════════════════════════════════════╝',
  '',
  '  ┌─ Email ──────────────────────────────────┐',
  '  │  hello@developer.dev                     │',
  '  └──────────────────────────────────────────┘',
  '  ┌─ GitHub ─────────────────────────────────┐',
  '  │  github.com/developer                    │',
  '  └──────────────────────────────────────────┘',
  '  ┌─ LinkedIn ───────────────────────────────┐',
  '  │  linkedin.com/in/developer               │',
  '  └──────────────────────────────────────────┘',
  '  ┌─ Portfolio ──────────────────────────────┐',
  '  │  developer.dev                           │',
  '  └──────────────────────────────────────────┘',
  '',
  '  Feel free to reach out! I\'m always happy to',
  '  chat about tech, projects, or opportunities.',
  '',
]

export const EDUCATION_TEXT = [
  '',
  '  ╔══════════════════════════════════════════╗',
  '  ║            EDUCATION                     ║',
  '  ╚══════════════════════════════════════════╝',
  '',
  '  ┌─ 2018 — 2022 ───────────────────────────┐',
  '  │ B.S. Computer Science                    │',
  '  │ University of Technology                 │',
  '  │ GPA: 3.8 / 4.0                          │',
  '  │                                          │',
  '  │ Relevant Coursework:                     │',
  '  │ • Data Structures & Algorithms           │',
  '  │ • Distributed Systems                    │',
  '  │ • Machine Learning                       │',
  '  │ • Database Systems                       │',
  '  │ • Computer Networks                      │',
  '  └──────────────────────────────────────────┘',
  '',
  '  ┌─ Certifications ─────────────────────────┐',
  '  │ • AWS Solutions Architect Associate      │',
  '  │ • Google Professional Cloud Developer    │',
  '  └──────────────────────────────────────────┘',
  '',
]

export const EXPERIENCE_TEXT = [
  '',
  '  ╔══════════════════════════════════════════╗',
  '  ║          WORK EXPERIENCE                 ║',
  '  ╚══════════════════════════════════════════╝',
  '',
  '  ┌─ 2023 — Present ─────────────────────────┐',
  '  │ Senior Software Engineer @ TechCorp      │',
  '  │                                           │',
  '  │ • Lead development of microservices       │',
  '  │   architecture serving 2M+ requests/day   │',
  '  │ • Reduced API response times by 40%       │',
  '  │ • Mentored team of 4 junior developers    │',
  '  │ • Stack: React, Node.js, PostgreSQL, AWS  │',
  '  └───────────────────────────────────────────┘',
  '',
  '  ┌─ 2022 — 2023 ────────────────────────────┐',
  '  │ Software Engineer @ StartupXYZ           │',
  '  │                                           │',
  '  │ • Built real-time analytics dashboard     │',
  '  │ • Implemented CI/CD pipeline with GitHub  │',
  '  │   Actions, reducing deploy time by 60%    │',
  '  │ • Developed REST APIs consumed by 50K+    │',
  '  │   daily active users                      │',
  '  │ • Stack: Vue.js, Python, MongoDB, Docker  │',
  '  └───────────────────────────────────────────┘',
  '',
  '  ┌─ 2021 — 2022 (Intern) ───────────────────┐',
  '  │ Software Engineering Intern @ BigTech     │',
  '  │                                           │',
  '  │ • Contributed to internal tooling used by  │',
  '  │   500+ engineers                           │',
  '  │ • Built automated testing framework       │',
  '  │ • Stack: Java, Spring Boot, React         │',
  '  └───────────────────────────────────────────┘',
  '',
]

export const NEOFETCH_TEXT = [
  '',
  '        ██████████████████         visitor@portfolio',
  '      ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██       ─────────────────',
  '    ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██     OS: Portfolio OS 2.0 x86_64',
  '  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██   Host: retro-terminal v2.0',
  '  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██   Kernel: React 19.1.0',
  '  ██▓▓▓▓██████▓▓▓▓██████▓▓▓▓██   Uptime: since you opened this tab',
  '  ██▓▓▓▓██  ██▓▓▓▓██  ██▓▓▓▓██   Packages: node_modules (∞)',
  '  ██▓▓▓▓██████▓▓▓▓██████▓▓▓▓██   Shell: interactive-terminal 1.0',
  '  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██   Resolution: whatever your screen is',
  '  ██▓▓▓▓▓▓▓▓████████▓▓▓▓▓▓▓▓██   Theme: CRT Phosphor Green',
  '    ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██     Terminal: retro-terminal',
  '      ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██       CPU: Caffeine-Powered @ ∞ GHz',
  '        ██████████████████         Memory: 42MB / ∞MB',
  '',
]

export const SUDO_TEXT = [
  '',
  '  🚨 PERMISSION DENIED 🚨',
  '',
  '  Nice try. This isn\'t your terminal to destroy.',
  '',
  '  But I appreciate the chaos energy.',
  '  Here, have a cookie instead: 🍪',
  '',
  '  Incident reported to /dev/null',
  '',
]

export const WEATHER_DATA = {
  seattle: {
    city: 'Seattle, WA',
    temp: '52°F / 11°C',
    condition: 'Overcast',
    wind: '12 mph NW',
    humidity: '82%',
    art: [
      '      .--.      ',
      '   .-(    ).    ',
      '  (___.__)__)   ',
      '   ///  ///     ',
      '  ///  ///      ',
    ],
  },
  tokyo: {
    city: 'Tokyo, Japan',
    temp: '73°F / 23°C',
    condition: 'Partly Cloudy',
    wind: '8 mph E',
    humidity: '55%',
    art: [
      '   \\  /        ',
      ' _ /"".-.       ',
      '   \\_(   ).    ',
      '   /(___(__) )  ',
      '              ',
    ],
  },
  miami: {
    city: 'Miami, FL',
    temp: '88°F / 31°C',
    condition: 'Sunny',
    wind: '6 mph SE',
    humidity: '70%',
    art: [
      '    \\   /      ',
      '     .-.        ',
      '  ‒ (   ) ‒    ',
      '     `-᾿        ',
      '    /   \\      ',
    ],
  },
  london: {
    city: 'London, UK',
    temp: '48°F / 9°C',
    condition: 'Foggy',
    wind: '15 mph W',
    humidity: '91%',
    art: [
      '  _ - _ - _ -   ',
      '   _ - _ - _    ',
      '  _ - _ - _ -   ',
      '   _ - _ - _    ',
      '  _ - _ - _ -   ',
    ],
  },
  denver: {
    city: 'Denver, CO',
    temp: '35°F / 2°C',
    condition: 'Snow',
    wind: '20 mph N',
    humidity: '75%',
    art: [
      '      .--.      ',
      '   .-(    ).    ',
      '  (___.__)__)   ',
      '   * * * *      ',
      '  * * * *       ',
    ],
  },
}

export const FORTUNE_QUOTES = [
  '"Any fool can write code that a computer can understand. Good programmers write code that humans can understand." — Martin Fowler',
  '"First, solve the problem. Then, write the code." — John Johnson',
  '"Experience is the name everyone gives to their mistakes." — Oscar Wilde',
  '"In order to be irreplaceable, one must always be different." — Coco Chanel',
  '"Java is to JavaScript what car is to carpet." — Chris Heilmann',
  '"Knowledge is power." — Francis Bacon',
  '"Fix the cause, not the symptom." — Steve Maguire',
  '"Simplicity is the soul of efficiency." — Austin Freeman',
  '"Before software can be reusable it first has to be usable." — Ralph Johnson',
  '"Make it work, make it right, make it fast." — Kent Beck',
  '"Code is like humor. When you have to explain it, it\'s bad." — Cory House',
  '"The best error message is the one that never shows up." — Thomas Fuchs',
  '"Deleted code is debugged code." — Jeff Sickel',
  '"It\'s not a bug — it\'s an undocumented feature." — Anonymous',
  '"The most disastrous thing that you can ever learn is your first programming language." — Alan Kay',
  '"The only way to learn a new programming language is by writing programs in it." — Dennis Ritchie',
  '"Talk is cheap. Show me the code." — Linus Torvalds',
  '"Programs must be written for people to read, and only incidentally for machines to execute." — Harold Abelson',
  '"Truth can only be found in one place: the code." — Robert C. Martin',
  '"Give a man a program, frustrate him for a day. Teach a man to program, frustrate him for a lifetime." — Muhammad Waseem',
  '"A language that doesn\'t affect the way you think about programming is not worth knowing." — Alan Perlis',
  '"Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday\'s code." — Dan Salomon',
  '"Measuring programming progress by lines of code is like measuring aircraft building progress by weight." — Bill Gates',
  '"Debugging is twice as hard as writing the code in the first place." — Brian Kernighan',
  '"The computer was born to solve problems that did not exist before." — Bill Gates',
]

export const ASCII_ART_COLLECTION = [
  {
    name: 'Cat',
    art: [
      '',
      '    /\\_/\\  ',
      '   ( o.o ) ',
      '    > ^ <  ',
      '   /|   |\\',
      '  (_|   |_)',
      '',
      '  meow~ 🐱',
      '',
    ],
  },
  {
    name: 'Rocket',
    art: [
      '',
      '        /\\',
      '       /  \\',
      '      |    |',
      '      |    |',
      '      | {} |',
      '      |    |',
      '     /|    |\\',
      '    / |    | \\',
      '   /__|    |__\\',
      '      |____|',
      '      /    \\',
      '     / /\\/\\ \\',
      '      \\/  \\/',
      '       \\  /',
      '        \\/  🚀',
      '',
    ],
  },
  {
    name: 'Coffee',
    art: [
      '',
      '       ( (  ',
      '        ) ) ',
      '      .....',
      '      |   |]',
      '      |   | ',
      '      `---\' ',
      '',
      '  But first, coffee ☕',
      '',
    ],
  },
  {
    name: 'Potato',
    art: [
      '',
      '       .-""""-.  ',
      '      /        \\ ',
      '     |  O    O  |',
      '     |  \\____/  |',
      '      \\        / ',
      '       `------\'  ',
      '',
      '  I\'m a potato 🥔',
      '',
    ],
  },
]
